@extends("user.app")
@section("content")
<style type="text/css">
.table {
    border: 1px solid #dcdcdc !important;
}
.table th, .table td {
    border: 1px !important;
}
.table td{
    border-right: 1px solid #dcdcdc !important;
}
.table thead td {
  border: 1px solid #dcdcdc !important;
}
.fixed-table-container {
    border:0px !important;
}
</style>
<div class="container-fluid">
<h1>LED/CFL Bulb List</h1>
<p>The following lightbulbs have been reviewed and approved for use with Jasco developed Z-Wave lighting controls.</p>
<table class="table" data-toggle="table" data-striped="true">
  <thead>
    <tr>
      <td><h4>Brand</h4></td>
      <td><h4>Type</h4></td>
      <td><h4>Wattage</h4></td>
      <td><h4>Shape</h4></td>
      <td><h4>Model</h4></td>
    </tr>
  </thead>
<tbody>
<tr>
<td>Array</td>
<td>LED</td>
<td>7.8W</td>
<td><span>BR30</span></td>
<td><span>AE26R3083025</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>2.5W</td>
<td><span>R16</span></td>
<td><span>AE26R163025</span></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Commercial Electric</td>
<td>LED</td>
<td>12W</td>
<td>
<p>6" Retrofit</p>
<p></p>
</td>
<td>CER608943WH30</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Cree</td>
<td>LED</td>
<td>6W</td>
<td>A19</td>
<td>BA19-045270MF</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>10W</td>
<td>A19</td>
<td>BA19-080270MB-12DE26-3C</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>12.5W</td>
<td>6" Retrofit </td>
<td>DRDL6-06227009-12DE26-1C100</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Ecosmart</td>
<td>LED</td>
<td>5.6W</td>
<td>A19</td>
<td>5bSA450STQ1D01</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>5.6W</td>
<td>A19</td>
<td>5bSA450STQ1D03</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>6W</td>
<td>A15</td>
<td>ECS A15 60WE CW</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>6.4W</td>
<td>A19</td>
<td>5aSA-A460ST</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>9W</td>
<td>A19</td>
<td>5bSAA800STQ1D01</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>9W</td>
<td>A19</td>
<td>5bSAA800STQ1D03</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>9W</td>
<td>A19</td>
<td>5bSAA800STQ1D02</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>9W</td>
<td>A19</td>
<td>5aSA-A810SS-Q1D-01</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>10.5W</td>
<td>BR30</td>
<td>1001372519</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>12.5W</td>
<td>A19</td>
<td>C5A19A75WESD04</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>13.5W</td>
<td>BR30</td>
<td>1003018802</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>15W</td>
<td>A21</td>
<td>5bSA1600STQ1D03</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>15W</td>
<td>A19</td>
<td>B6A19100WESD01</td>
</tr>
<tr>
<td></td>
<td>CFL</td>
<td>15W</td>
<td>T3</td>
<td>FLE15HT3/2/DV/SW</td>
</tr>
<tr>
<td></td>
<td>CFL</td>
<td>26W</td>
<td>T3</td>
<td>FLE26HT3/2/DV/SW</td>
</tr>
<tr>
<td></td>
<td>CFL</td>
<td>26W</td>
<td>R40</td>
<td>FLE26/2/DV/R40</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Feit Electric</td>
<td>LED</td>
<td>9.8W</td>
<td>A19</td>
<td>OM60/927/LED/2</td>
</tr>
<tr>
<td></td>
<td></td>
<td>15.5W</td>
<td>PAR38</td>
<td>PAR38/930/LEDG11</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>General Electric</td>
<td>LED</td>
<td>6W</td>
<td>A19</td>
<td>LED6DA19/5K/BX</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>7W</td>
<td>
<p>PAR20</p>
</td>
<td>
<p>LED7DP20S827/20</p>
</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>10W</td>
<td>PAR30</td>
<td>LED10DP30S830/20</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>10.5W</td>
<td>A19</td>
<td>LED11DAV3RVL2PLT</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>10.5W</td>
<td>A19</td>
<td>LED11DAV3/827W</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>11W</td>
<td>A19</td>
<td>LED11DA19/827</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>12W</td>
<td><span>BR30</span></td>
<td><span>LED12DBR30/827</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>12W</td>
<td><span>PAR38</span></td>
<td><span>LED12DP38S830/35</span></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Great Value</td>
<td>Filament LED</td>
<td>7W</td>
<td>A19</td>
<td>A19D4.5W22G</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>7W</td>
<td>PAR16</td>
<td>GVRLP16730D3</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>7W</td>
<td>A19</td>
<td><span>GVRLAO727D</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>7W</td>
<td></td>
<td>A19016</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>7W</td>
<td></td>
<td>A13016</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>9.5W</td>
<td>A19</td>
<td><span>A190060 (GVRLA1027DC2)</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>9.9W</td>
<td>A19</td>
<td><span>GVRLA1050DC2</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>10W</td>
<td>A19</td>
<td><span>GVRLA01050D</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>10W</td>
<td>A19</td>
<td><span>A19023</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>10W</td>
<td>A19</td>
<td><span>A1902301</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>13W</td>
<td>PAR38</td>
<td><span>GVP38120DW2</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>18W</td>
<td>A21</td>
<td><span>LED18A21D0D</span></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Osram Sylvania</td>
<td>Filament LED</td>
<td>4.5W</td>
<td>A19</td>
<td>LED4.5A19/DIM/827/FIL/RP</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>5.5W</td>
<td>A19</td>
<td><span>LED5.5A19/DIM/0/850/U/RP2/ZH</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>6.5W</td>
<td>A19</td>
<td><span>LED6.5A19DIM827G5</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>8W</td>
<td>PAR20</td>
<td><span>LED8PAR20/DIM/H/830/FL36</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>8W</td>
<td>A19</td>
<td><span>LED8A/DIM/F/827</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>8W</td>
<td>PAR20</td>
<td><span>LED8PAR20/DIM/827/FL36</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>8.5W</td>
<td></td>
<td><span>4613579161</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>8.5W</td>
<td>A19</td>
<td><span>LED8.5A19/DIM/0/850/G5/RP</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>10W</td>
<td>5"/6" Retrofit</td>
<td><span>75329</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>10W</td>
<td>PAR20</td>
<td><span>LED10PAR20/DIM/P/930/FL30</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>11W</td>
<td>PAR30</td>
<td><span>LED11PAR30DIMSG830NFL25</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>14W</td>
<td></td>
<td><span>CF14EL/TWIST/DIM</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>15W</td>
<td>PAR30</td>
<td><span>LED15PAR30/DIM/830/NFL25</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>15W</td>
<td>PAR30</td>
<td><span>LED15PAR30LN/DIM/830/NFL25</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>15W</td>
<td>PAR30</td>
<td><span>LED15PAR30LN/DIM/827/FL40</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>15W</td>
<td>BR30</td>
<td><span>LED15BR30/DIM/827</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>17W</td>
<td>PAR30</td>
<td><span>LED17PAR30LN/DIM/P/930/NFL25</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>18W</td>
<td>PAR38</td>
<td><span>LED18PAR38/DIM/830/NFL25</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>18W</td>
<td>PAR38</td>
<td><span>LED18PAR38/DIM/827/FL40</span></td>
</tr>
<tr>
<td></td>
<td>CFL</td>
<td>24W</td>
<td></td>
<td><span>CF24EL/TWIST/DIM</span></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Philips</td>
<td>LED</td>
<td>6W</td>
<td>A19</td>
<td>9290011348</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>8W</td>
<td>BR30</td>
<td>BC8BR30/AMB/850/DIM</td>
</tr>
<tr>
<td></td>
<td>Filament LED</td>
<td>8.5W</td>
<td>A19</td>
<td>8.5A19/AMB/822-827/CL/GL/DIM</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>9.5W</td>
<td>A19</td>
<td><span>9290011345</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>11W</td>
<td>4" Retrofit</td>
<td>592353IU0</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>14W</td>
<td>PAR38</td>
<td>14PAR38/AMB/830/F40/GL/DIM/BC</td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>18W</td>
<td>A21</td>
<td>BC18A21/AMB/827-22/DIM</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Utilitech</td>
<td>LED</td>
<td>7.5W</td>
<td>A19</td>
<td><span>LA19DM/5K/LED</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>7.5W</td>
<td>PAR20</td>
<td><span>LPAR20DM/LED</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>8.5W</td>
<td>A19</td>
<td><span>YGA03A37-8.5W-D-830</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>10W</td>
<td>BR30</td>
<td><span>YGA08A48-BR30-10W-850-1</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>10W</td>
<td>G25</td>
<td><span>LG25DM/LED</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>13W</td>
<td>A19</td>
<td><span>LA19DM/800/LED</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>13.5W</td>
<td>A19</td>
<td><span>LA19/OM800/LED</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>15W</td>
<td>GU24 Pin Base</td>
<td><span>LBP13T/GU24/DM/27K</span></td>
</tr>
<tr>
<td></td>
<td>LED</td>
<td>18W</td>
<td>PAR38</td>
<td><span>LPAR38DM/5K/LED</span></td>
</tr>
</tbody>
</table>
</div>
@endsection
  